.ORIG x3000
; OUTPUT PROMPT
BEGIN LDI R0, PROMPT
PUTS 

; GET INPUT
GETC ; STORES AN ASCII VAL FROM KEYBOARD

; CONVERT ASCII TO NUMBER 
ADD R0, R0, -16
ADD R0, R0, -16
ADD R0, R0, -16

; COPY R0 TO R6 
ADD R6, R0, R0 ; STORE NUMBER IN R6

;;;;
;COMPARE NUMBER TO ANSWER 
LD R1, ANSWER
NOT R0 R1 
ADD R0 R0 1
ADD R0 R6 R0 

BRz CORRECT
BRp BIGGER 
BRn SMALLER  
CORRECT LDI R0, CORRECT1
PUTS 

ADD R6 R6 16
ADD R6 R6 16
ADD R6 R6 16
ADD R0 R6 0
OUT 

LDI R0 CORRECT2 
PUTS
HALT

BIGGER LD R0 BIG 
PUTS 
BRnzp BEGIN 

SMALLER LD R0 SMALL 
PUTS 
BRnzp BEGIN


ANSWER	   .FILL x0006
NEWLINE    .FILL x00A0
PTR        .FILL x4000
PROMPT	   .STRINGZ "Guess a number between 0 & 9" 
SMALL	   .STRINGZ "Too small" 
BIG 	   .STRINGZ "Too Big" 
CORRECT1   .STRINGZ "Correct! You took "
CORRECT2   .STRINGZ " guesses."